CAT-main/Models/ViewModels/QuoteCalculatorViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CAT.Models.ViewModels
{
    public class QuoteCalculatorViewModel
    {
        [Required]
        public string? SourceLanguage { get; set; }

        [Required]
        public List<String>? TargetLanguages { get; set; }

        [Required]
        public int Speciality { get; set; }
        [Required]

        public int Filter { get; set; }

        public IFormFile? FileToUpload { get; set; }

        public int ServiceSpeed { get; set; }

        public Dictionary<string, string> Languages => new Dictionary<string, string>
        {
            {"nl", "Dutch"},
            {"de", "German"},
            {"en", "English"},
            {"fr", "French"},
            {"it", "Itaian"},
            {"es", "Spanish"}
            // Add more languages as needed
        };

        public Dictionary<int, string> Specialities => new Dictionary<int, string>
        {
            {1, "General"},
            {2, "Marketing"},
            {3, "Technical"}
        };
    }
}

CAT-main/Models/ViewModels/StoredQuoteDetailsViewModel.cs
using CAT.Enums;
using CAT.Models.Entities.Main;

namespace CAT.Models.ViewModels
{
    public class StoredQuoteDetailsViewModel
    {
        public StoredQuoteDetailsViewModel()
        {
            Specialities = Enum.GetValues(typeof(Speciality))
                                           .Cast<Speciality>()
                                           .ToDictionary(e => (int)e, e => e.ToString());
        }

        public StoredQuote StoredQuote { get; set; } = default!;
        public Dictionary<int, string> Specialities { get; set; } = default!;
    }
}

CAT-main/Controllers/Mvc/QuoteCalculatorController.cs
using AutoMapper;
using CAT.Data;
using CAT.Enums;
using CAT.Helpers;
using CAT.Models.Common;
using CAT.Models.Entities.Main;
using CAT.Models.ViewModels;
using CAT.Services.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.Xml;
using System.Transactions;

namespace CAT.Controllers.Mvc
{
    public class QuoteCalculatorController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IQuoteService _quoteService;
        private readonly IDocumentService _documentService;
        private readonly IOrderService _orderService;
        private readonly IMapper _mapper;
        private readonly ILogger _logger;

        public QuoteCalculatorController(DbContextContainer dbContextContainer, IConfiguration configuration, IQuoteService quoteService,
            IDocumentService documentService, IOrderService orderService, IMapper mapper, ILogger<JobService> logger)
        {
            _configuration = configuration;
            _quoteService = quoteService;
            _documentService = documentService;
            _orderService = orderService;
            _logger = logger;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var storedQuotes = await _quoteService.GetStoredQuotesAsync(DateTime.MinValue, DateTime.MaxValue);
            var storedQuotesViewModel = new StoredQuotesViewModel()
            {
                StoredQuotes = storedQuotes
            };

            return View(storedQuotesViewModel);
            //return RedirectToAction("QuoteDetails"); // or wherever you want to redirect
        }

        //[HttpPost]
        //public IActionResult Index(QuoteCalculatorViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        // Process the uploaded file and other data as needed
        //        // Save to database, call another service, etc.
        //        return RedirectToAction("Success"); // or wherever you wish to redirect after processing
        //    }

        //    return View(model);
        //}

        [HttpPost]
        public async Task<IActionResult> HandleQuote(CreateQuoteViewModel model, string action)
        {

            if (!ModelState.IsValid)
            {
                return View("Create", model);
            }

            switch (action)
            {
                case "CalculateQuote":
                    var storedQuoteId = model.StoredQuoteId;
                    try
                    {
                        //using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled)) //MSDTC
                        //using (var transaction = context.Database.BeginTransaction())
                        {
                            //create stored quote if doesn't exists
                            var clientId = -1;
                            if (model.StoredQuoteId <= 0)
                            {
                                var stroedQuote = await _quoteService.CreateStoredQuoteAsync(clientId);
                                storedQuoteId = stroedQuote.Id;
                            }

                            int idFilter = -1;
                            var document = await _documentService.CreateTempDocumentAsync(model.FileToUpload!, DocumentType.Original, idFilter);
                            //create the quote
                            var targetLocales = model.TargetLanguages!.Select(lang => new LocaleId(lang)).ToArray();
                            var quotes = await _quoteService.CreateTempQuotesAsync(storedQuoteId, 1, new LocaleId(model.SourceLanguage!), targetLocales,
                                model.Speciality, model.Service, document.Id);

                            //scope.Complete();
                        }

                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError(string.Empty, "An error occurred while calculating the quote. Please try again.");
                        return View("Create", model);
                    }

                    return RedirectToAction("StoredQuoteDetails", new { storedQuoteId });
                default:
                    return View("Create", model);
            }
        }

        [Route("QuoteCalculator/Create/{storedQuoteId?}")]
        public async Task<IActionResult> Create(int? storedQuoteId)
        {
            storedQuoteId = storedQuoteId ?? -1;
            var createQuoteViewModel = new CreateQuoteViewModel();
            createQuoteViewModel.StoredQuoteId = (int)storedQuoteId;

            return View(createQuoteViewModel);
        }

        //[HttpGet()]
        //[HttpGet("{idStoredQuote?}")]
        [Route("QuoteCalculator/StoredQuoteDetails/{storedQuoteId?}")]
        public async Task<IActionResult> StoredQuoteDetails(int? storedQuoteId)
        {
            storedQuoteId = storedQuoteId ?? -1;
            var storedQuote = await _quoteService.GetStoredQuoteAsync((int)storedQuoteId);

            var storedQuoteViewModel = new StoredQuoteDetailsViewModel();

            storedQuoteViewModel.StoredQuote = storedQuote!;
            return View(storedQuoteViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> LaunchStoredQuote(int id)
        {
            await _orderService.LaunchStoredQuotesAsync(id);
            var storedQuoteViewModel = new StoredQuoteDetailsViewModel();

            var storedQuote = await _quoteService.GetStoredQuoteAsync(id);
            storedQuoteViewModel.StoredQuote = storedQuote!;
            return View("StoredQuoteDetails", storedQuoteViewModel);
        }
    }
}

CAT-main/Views/QuoteCalculator/Index.cshtml
@model StoredQuotesViewModel
@{
    ViewBag.Title = "Quote Calculator";
}

<style>
</style>

@section Scripts {
}

<h2>Quotes</h2>

<form method="post" asp-action="LaunchQuote">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Client
                </th>
                <th>
                    Date created
                </th>
                <th>
                    Order
                </th>
                <th>
                    Fee
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.StoredQuotes != null)
            {
                @foreach (var storedQuote in Model.StoredQuotes)
                {
                    <tr>
                        <td>
                            <a href="#">Test Account</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => storedQuote.DateCreated)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => storedQuote.OrderId)
                        </td>
                        <td>
                            £@Html.DisplayFor(modelItem => storedQuote.Fee)
                        </td>
                        <td>
                            @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
                            <a asp-action="StoredQuoteDetails" asp-route-storedQuoteId="@storedQuote.Id">Details</a> |
                            <a asp-action="StoredQuoteDelete" asp-route-storedQuoteId="@storedQuote.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</form>

CAT-main/Views/QuoteCalculator/QuoteDetails.cshtml
@model StoredQuoteViewModel
@{
    ViewBag.Title = "Quote Details";
}

<h2>Quote Details</h2>

<p><b>Client:</b> @(Model.StoredQuote?.ClientId > 0 ? Model.StoredQuote.ClientId.ToString() : "N/A")</p>
<p><b>Order:</b> @(Model.StoredQuote?.OrderId > 0 ? Model.StoredQuote.OrderId.ToString() : "N/A")</p>

@if (Model.StoredQuote?.OrderId > 0)
{
    <p>Date: @(Model.StoredQuote?.DateCreated != null ? Model.StoredQuote.DateCreated.ToString() : "N/A")</p>
}

<p><b>Price total:</b> £@Model.Fee.ToString("N2")</p>

<!-- Add other properties as needed -->

<form method="post" asp-action="LaunchQuote">
    <input type="hidden" name="id" value="@Model.StoredQuote?.Id" />
    <a asp-action="Create" asp-controller="QuoteCalculator" asp-route-storedQuoteId="@Model.StoredQuote?.Id">
        @(Model.StoredQuote?.Id > 0 ? "Add New" : "Create New")
    </a>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Document
                </th>
                <th>
                    Source language
                </th>
                <th>
                    Target language
                </th>
                <th>
                    Speciality
                </th>
                <th>
                    Speed
                </th>
                <th>
                    Fee
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.StoredQuote?.TempQuotes != null)
            {
                @foreach (var item in Model.StoredQuote!.TempQuotes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TempDocument.OriginalFileName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SourceLanguage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TargetLanguage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Specialities[item.SpecialityId])
                        </td>
                        <td>
                            @(((CAT.Enums.ServiceSpeed)item.Speed).ToString())
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fee)
                        </td>
                        <td>
                            @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

    @if (Model.StoredQuote?.TempQuotes?.Count > 0)
    {
        <button type="submit" class="btn btn-success">Launch Quote</button>
    }
</form>

@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div class="alert alert-success mt-3">
        @ViewBag.Message
    </div>
}

CAT-main/Views/QuoteCalculator/StoredQuoteDetails.cshtml
@model StoredQuoteDetailsViewModel
@{
    ViewBag.Title = "Quote Details";
}

<h2>Quote Details</h2>

<p><b>Client:</b> @(Model.StoredQuote?.ClientId > 0 ? Model.StoredQuote.ClientId.ToString() : "N/A")</p>
<p><b>Order:</b> @(Model.StoredQuote?.OrderId > 0 ? Model.StoredQuote.OrderId.ToString() : "N/A")</p>

@if (Model.StoredQuote?.OrderId > 0)
{
    <p>Date: @(Model.StoredQuote?.DateCreated != null ? Model.StoredQuote.DateCreated.ToString() : "N/A")</p>
}

<p><b>Price total:</b> £@Model.StoredQuote?.Fee.ToString("N2")</p>

<!-- Add other properties as needed -->

<form method="post" asp-action="LaunchStoredQuote">
    <input type="hidden" name="id" value="@Model.StoredQuote?.Id" />
    <a asp-action="Create" asp-controller="QuoteCalculator" asp-route-storedQuoteId="@Model.StoredQuote?.Id">
        @(Model.StoredQuote?.Id > 0 ? "Add New" : "Create New")
    </a>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Document
                </th>
                <th>
                    Source language
                </th>
                <th>
                    Target language
                </th>
                <th>
                    Speciality
                </th>
                <th>
                    Speed
                </th>
                <th>
                    Service
                </th>
                <th>
                    Client review
                </th>
                <th>
                    Fee
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.StoredQuote?.TempQuotes != null)
            {
                @foreach (var item in Model.StoredQuote!.TempQuotes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TempDocument.OriginalFileName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SourceLanguage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TargetLanguage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Specialities[item.SpecialityId])
                        </td>
                        <td>
                            @(((CAT.Enums.ServiceSpeed)item.Speed).ToString())
                        </td>
                        <td>
                            @(((CAT.Enums.Service)item.Service).ToString())
                        </td>
                        <td>
                            @(item.ClientReview.ToString())
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fee)
                        </td>
                        <td>
                            @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

    @if (Model.StoredQuote?.TempQuotes?.Count > 0)
    {
        <button type="submit" class="btn btn-success">Launch Quote</button>
    }
</form>

@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div class="alert alert-success mt-3">
        @ViewBag.Message
    </div>
}