.Net/CAT-main/Areas/BackOffice/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using CAT.Data;
using CAT.Areas.Identity.Data;
using CAT.Helpers;
using CAT.Models.Entities.Main;
using CAT.Enums;
using CAT.Models.ViewModels;
using CAT.Services.Common;
using AutoMapper;
using Task = CAT.Enums.Task;
using CAT.Areas.BackOffice.Models.ViewModels;
using Hangfire;

namespace CAT.Areas.BackOffice.Controllers
{
    [Area("BackOffice")]
    public class JobsController : Controller
    {
        private readonly DbContextContainer _dbContextContainer;
        private readonly IConfiguration _configuration;
        private readonly IJobService _jobService;
        private readonly IMapper _mapper;
        private readonly ILogger _logger;

        public JobsController(DbContextContainer dbContextContainer, MainDbContext mainDbContext, TranslationUnitsDbContext translationUnitsDbContext,
            IConfiguration configuration, IJobService jobService, IMapper mapper, ILogger<JobService> logger)
        {
            _dbContextContainer = dbContextContainer;
            _configuration = configuration;
            _jobService = jobService;
            _logger = logger;
            _mapper = mapper;
        }

        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            try
            {
                // Check if TempData contains the ErrorMessage
                if (TempData.ContainsKey("ErrorMessage"))
                {
                    // Retrieve the error message from TempData and store it in a ViewBag
                    ViewBag.ErrorMessage = TempData["ErrorMessage"] as string;

                    // Clear the TempData entry to prevent the message from persisting across additional requests
                    TempData.Remove("ErrorMessage");
                }

                var jobsViewModels = await (from job in _dbContextContainer.MainContext.Jobs
                                            join document in _dbContextContainer.MainContext.Documents on job.SourceDocumentId equals document.Id
                                            select new JobViewModel
                                            {
                                                Id = job.Id,
                                                Analysis = "",
                                                DateCreated = job.Order!.DateCreated,
                                                Fee = job.Quote!.Fee,
                                                OriginalFileName = document.OriginalFileName
                                            }).ToListAsync();

                return View(jobsViewModels);
            }
            catch (Exception ex)
            {
                return Problem(ex.Message);
            }
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _dbContextContainer.MainContext.Jobs == null)
            {
                return NotFound();
            }

            var jobsViewModels = await (from job in _dbContextContainer.MainContext.Jobs
                                        join document in _dbContextContainer.MainContext.Documents on job.SourceDocumentId equals document.Id
                                        where job.Id == id
                                        select new JobViewModel
                                        {
                                            Id = job.Id,
                                            Analysis = "",
                                            DateCreated = job.Order!.DateCreated,
                                            Fee = job.Quote!.Fee,
                                            OriginalFileName = document.OriginalFileName
                                        }).FirstOrDefaultAsync();

            if (jobsViewModels == null)
            {
                return NotFound();
            }

            return View(jobsViewModels);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file, IFormFile fileFilter, string sourceLang, string targetLang)
        {
            try
            {
                if (file != null && file.Length > 0)
                {
                    //save the file
                    var sourceFilesFolder = Path.Combine(_configuration["SourceFilesFolder"]!);
                    // Generate a unique file name based on the original file name
                    string fileName = FileHelper.GetUniqueFileName(file.FileName);

                    // Combine the unique file name with the server's path to create the full path
                    string filePath = Path.Combine(sourceFilesFolder, fileName);

                    // Save the file to the server
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    var filterName = "";
                    if (fileFilter != null && fileFilter.Length > 0)
                    {
                        var fileFiltersFolder = Path.Combine(_configuration["FileFiltersFolder"]!);
                        // Generate a unique file name based on the original file name
                        filterName = FileHelper.GetUniqueFileName(fileFilter.FileName);

                        // Combine the unique file name with the server's path to create the full path
                        string filterPath = Path.Combine(fileFiltersFolder, filterName);
                        using (var stream = new FileStream(filterPath, FileMode.Create))
                        {
                            await fileFilter.CopyToAsync(stream);
                        }
                    }

                    //create doc
                    var document = new Document()
                    {
                        OriginalFileName = file.FileName,
                        FileName = fileName,
                        DocumentType = 0,
                    };

                    // Save the job
                    _dbContextContainer.MainContext.Documents.Add(document);
                    await _dbContextContainer.MainContext.SaveChangesAsync();

                    var quote = new Quote()
                    {
                        SourceLanguage = 1,
                        TargetLanguage = 2,
                        Fee = 10.0,
                        DateCreated = DateTime.Now,
                        Speciality = 0
                    };

                    var order = new Order()
                    {
                        DateCreated = DateTime.Now,
                        ClientId = 0,
                    };

                    var job = new Job()
                    {
                        Quote = quote,
                        Order = order,
                        SourceDocumentId = document.Id
                    };

                    //Save the order
                    _dbContextContainer.MainContext.Orders.Add(order);

                    //Save the quote
                    _dbContextContainer.MainContext.Quotes.Add(quote);

                    // Save the job
                    _dbContextContainer.MainContext.Jobs.Add(job);
                    await _dbContextContainer.MainContext.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                    throw new Exception("File is empty.");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"An error occurred: {ex.Message}";
                return View();
                //return Problem($"An error occurred: {ex.Message}", statusCode: 500);
            }
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _dbContextContainer.MainContext.Jobs == null)
            {
                return NotFound();
            }

            var job = await _dbContextContainer.MainContext.Jobs.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OriginalFileName,FileName,DateCreated,Analysis,Fee")] Job job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbContextContainer.MainContext.Update(job);
                    await _dbContextContainer.MainContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

.Net/CAT-main/Areas/LinguistsPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@Html.AntiForgeryToken()
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="XSRF-TOKEN" content="@Context.Request.Cookies["XSRF-TOKEN"]">

    <title>@ViewData["Title"] - CAT</title>

    <!-- Font awesome CSS CDN -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet" />

    <!-- Bootstrap CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-success-subtle">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Linguist portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="ClientsPortal" asp-controller="Jobs" asp-action="Jobs">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="ClientsPortal" asp-controller="Credits" asp-action="Jobs">Credit history</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="ClientsPortal" asp-controller="Users" asp-action="Jobs">Settings</a>
                        </li>
                    </ul>
                    <div class="ms-auto">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CAT main app - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap JS, Popper.js CDN (for certain Bootstrap components like modals, tooltips) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @if (Context.Items.ContainsKey("RequiresValidation"))
    {
        <text>
            <!-- Add jQuery Validate -->
            <script src=https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/1.1.2/js/bootstrap-multiselect.min.js"></script>

            <!-- Add jQuery Validate Unobtrusive -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
        </text>
    }

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>